language: java
deploy:
  provider: heroku
  api_key:
    secure: "d6f37711-ecb6-4e38-ab42-c38de48edd24"
  app: rest-servlet
notifications:
  email:
    recipients:
      - borninger@yandex.ru
    on_success: always
    on_failure: always