language: java
deploy:
  provider: heroku
  api_key:
    secure: "b58ccdbf-bc2a-4980-9528-09027001bda6"
  app: rest-servlet
notifications:
  email:
    recipients:
      - borninger@yandex.ru
    on_success: always
    on_failure: always