language: java
deploy:
  provider: heroku
  api_key:
    secure: c30c4cf8-0881-4ecb-9d15-ef7711f7a9ef
  app: rest-servlet
notifications:
  email:
    recipients:
      - borninger@yandex.ru
    on_success: always
    on_failure: always